### ISSUE TITLE
Létrehozni 

### ISSUE THREAD

**Issue by HaLTeX1** [NemodaMark/AstraDrive#7]
- Quiz
- Copyright page kartyak
- Profil (Garázs) page
- Astra adatbazis

**Comment by HaLTeX1** [comment]
QUIZ kész

**Comment by NemodaMark** [comment]
Profil 80%-os kb (hiányoznak a gombokról az akciók, PROFIL SZERKESZTÉS, JS még hülye)

**Comment by NemodaMark** [comment]
Az adatbázisban hiányoznak adatok
